// LicensePK Question Bank
// Categories: Road Signs, Traffic Rules, Right of Way, Penalties
const QUESTIONS = [
  // ROAD SIGNS
  { id: "sign_01", category: "Road Signs", question_en: "A circular red sign with a white horizontal bar means:", question_ur: "Gol laal sign jis mein safaid horizontal bar ho uska matlab:", options: ["No Entry", "Stop", "Give Way", "Speed Limit"], correctIndex: 0, explanation: "A red circle with a white bar is the universal 'No Entry' sign, meaning vehicles are prohibited from entering that road." },
  { id: "sign_02", category: "Road Signs", question_en: "A triangular sign with a red border is used for:", question_ur: "Laal border wala triangle sign kis liye use hota hai:", options: ["Mandatory instructions", "Warning of hazard ahead", "Informational sign", "Parking sign"], correctIndex: 1, explanation: "Triangular signs with red borders are warning signs, alerting drivers to hazards like curves, crossings, or narrow roads ahead." },
  { id: "sign_03", category: "Road Signs", question_en: "An octagonal (8-sided) red sign means:", question_ur: "Athkoni (8 sides) laal sign ka matlab:", options: ["Yield", "Stop completely", "No parking", "One way"], correctIndex: 1, explanation: "The octagon shape is reserved exclusively for the STOP sign worldwide, requiring a complete stop before proceeding." },
  { id: "sign_04", category: "Road Signs", question_en: "A blue circular sign generally indicates:", question_ur: "Neela gol sign aam tor par kya batata hai:", options: ["A warning", "A mandatory instruction", "A prohibition", "A tourist spot"], correctIndex: 1, explanation: "Blue circles are mandatory instruction signs, such as 'Turn Left Ahead' or 'Minimum Speed Limit' — you must follow them." },
  { id: "sign_05", category: "Road Signs", question_en: "A sign showing a black car overtaking within a red circle means:", question_ur: "Laal circle mein overtaking car ka sign kya matlab rakhta hai:", options: ["Overtaking allowed", "No overtaking", "Slow down", "Two-way traffic"], correctIndex: 1, explanation: "This sign explicitly prohibits overtaking other vehicles on that stretch of road, usually due to poor visibility or narrow lanes." },
  { id: "sign_06", category: "Road Signs", question_en: "A rectangular blue sign with a white 'P' indicates:", question_ur: "Neeli rectangle sign jis mein safaid 'P' ho:", options: ["Petrol station", "Parking area", "Pedestrian crossing", "Police station"], correctIndex: 1, explanation: "The letter 'P' on a blue rectangular background universally signals a designated parking area." },
  { id: "sign_07", category: "Road Signs", question_en: "A yellow diamond-shaped sign with a pedestrian symbol means:", question_ur: "Peela diamond sign jis mein pedestrian ho:", options: ["No pedestrians allowed", "Pedestrian crossing ahead", "School zone", "Hospital nearby"], correctIndex: 1, explanation: "This warns drivers of an upcoming pedestrian crossing, requiring extra caution and reduced speed." },
  { id: "sign_08", category: "Road Signs", question_en: "A sign with two arrows pointing in opposite directions indicates:", question_ur: "Do arrows jo mukhtalif directions mein ho, uska matlab:", options: ["One-way road", "Two-way traffic ahead", "Dead end", "Roundabout"], correctIndex: 1, explanation: "This warns that the road ahead carries traffic moving in both directions, so drivers should stay in their lane." },
  { id: "sign_09", category: "Road Signs", question_en: "A sign showing a fuel pump icon means:", question_ur: "Fuel pump wala sign kya batata hai:", options: ["Petrol station ahead", "No fuel allowed", "Car wash", "Toll booth"], correctIndex: 0, explanation: "This informational sign tells drivers a fuel/petrol station is located ahead." },
  { id: "sign_10", category: "Road Signs", question_en: "A red circle with a black car and another black car beside it, both crossed out, means:", question_ur: "Laal circle mein 2 cars cross ki hui:", options: ["No overtaking of any vehicle", "No parking", "No U-turn", "No trucks allowed"], correctIndex: 0, explanation: "This sign bans overtaking any vehicle on this road segment, common on hilly or blind-curve roads." },

  // TRAFFIC RULES
  { id: "rule_01", category: "Traffic Rules", question_en: "What is the speed limit in a populated area?", question_ur: "Populated area mein speed limit kitni hoti hai:", options: ["40 km/h", "50 km/h", "70 km/h", "100 km/h"], correctIndex: 2, explanation: "Per the NH&MP theoretical test syllabus, the speed limit in a populated area is 70 km/h." },
  { id: "rule_01b", category: "Traffic Rules", question_en: "What is the speed limit near a Mosque or School?", question_ur: "Masjid ya school ke qareeb speed limit kitni hoti hai:", options: ["40 km/h", "50 km/h", "70 km/h", "80 km/h"], correctIndex: 0, explanation: "Speed must be reduced to 40 km/h near Mosques and Schools, where pedestrian activity is high." },
  { id: "rule_02", category: "Traffic Rules", question_en: "When approaching a roundabout, who has the right of way?", question_ur: "Roundabout par kisko pehle jaane ka haq hota hai:", options: ["Vehicles entering the roundabout", "Vehicles already inside the roundabout", "Whoever arrives first", "Larger vehicles"], correctIndex: 1, explanation: "Vehicles already circulating inside the roundabout have priority; entering traffic must yield to them." },
  { id: "rule_03", category: "Traffic Rules", question_en: "Using a mobile phone while driving without hands-free is:", question_ur: "Gaari chalatay waqt bina hands-free mobile use karna:", options: ["Allowed if stopped at a signal", "Illegal and unsafe", "Allowed for emergency calls only", "Allowed at low speed"], correctIndex: 1, explanation: "Handheld mobile phone use while driving is illegal in Pakistan and significantly increases accident risk due to distraction." },
  { id: "rule_04", category: "Traffic Rules", question_en: "Seat belts are mandatory for:", question_ur: "Seat belt lagana zaroori hai:", options: ["Only the driver", "Driver and front passenger", "Only on motorways", "Only for long trips"], correctIndex: 1, explanation: "Both the driver and front-seat passenger are legally required to wear seat belts at all times while the vehicle is moving." },
  { id: "rule_05", category: "Traffic Rules", question_en: "What should you do when an ambulance with a siren approaches from behind?", question_ur: "Peechay se ambulance siren ke saath aaye to kya karna chahiye:", options: ["Speed up to clear the way", "Pull over safely and let it pass", "Ignore it if you're in a hurry", "Stop immediately in your lane"], correctIndex: 1, explanation: "You must safely move aside to give way to emergency vehicles, never stop abruptly in your current lane." },
  { id: "rule_06", category: "Traffic Rules", question_en: "Overtaking on the left side of a vehicle is:", question_ur: "Left side se overtake karna:", options: ["Always allowed", "Generally prohibited and unsafe", "Only allowed at night", "Only allowed for bikes"], correctIndex: 1, explanation: "Overtaking should be done from the right; overtaking from the left is unsafe and generally prohibited except in specific lane situations." },
  // NOTE: not confirmed against the NH&MP theoretical test syllabus (it doesn't cover minimum age).
  // Commonly cited as 18, but verify against your provincial licensing authority before treating this as certain.
  { id: "rule_07", category: "Traffic Rules", question_en: "The minimum age to apply for a car learner's license in Pakistan is:", question_ur: "Pakistan mein car learner license ke liye minimum age:", options: ["16 years", "18 years", "21 years", "25 years"], correctIndex: 1, explanation: "You must be at least 18 years old to apply for a car learner's permit in Pakistan (verify with your provincial licensing authority)." },
  { id: "rule_08", category: "Traffic Rules", question_en: "What does a solid white line in the middle of the road mean?", question_ur: "Road ke beech mein solid white line ka matlab:", options: ["Overtaking allowed", "Overtaking not allowed", "Parking permitted", "Pedestrian zone"], correctIndex: 1, explanation: "A solid line indicates you should not cross to overtake, usually due to reduced visibility ahead." },
  { id: "rule_09", category: "Traffic Rules", question_en: "Before changing lanes, a driver must:", question_ur: "Lane change karne se pehle driver ko kya karna chahiye:", options: ["Just change quickly", "Check mirrors and indicate", "Honk loudly", "Slow down to a stop"], correctIndex: 1, explanation: "Always check mirrors, blind spots, and use indicators before changing lanes to alert other drivers safely." },
  { id: "rule_10", category: "Traffic Rules", question_en: "Driving under the influence of alcohol is:", question_ur: "Sharab pi kar gaari chalana:", options: ["Allowed in small quantity", "Strictly illegal", "Allowed after 10pm", "Allowed on motorways only"], correctIndex: 1, explanation: "Driving under the influence of alcohol is strictly illegal in Pakistan and carries serious legal penalties." },

  // RIGHT OF WAY
  { id: "row_01", category: "Right of Way", question_en: "At an uncontrolled intersection (no signal, no sign), who has the right of way?", question_ur: "Bina signal/sign wale intersection par right of way kiska hota hai:", options: ["Vehicle on the right", "Vehicle on the left", "Whoever honks first", "Larger vehicle"], correctIndex: 0, explanation: "At uncontrolled intersections, the general convention is to yield to traffic approaching from your right." },
  { id: "row_02", category: "Right of Way", question_en: "Pedestrians on a marked crossing (zebra crossing) have right of way over:", question_ur: "Zebra crossing par pedestrians ka right of way kis par hota hai:", options: ["No one, cars have priority", "Vehicles", "Only cyclists", "Only during the day"], correctIndex: 1, explanation: "Pedestrians using a marked zebra crossing have the right of way, and vehicles must stop to let them cross safely." },
  { id: "row_03", category: "Right of Way", question_en: "When two vehicles arrive at a 4-way stop at the same time, who goes first?", question_ur: "4-way stop par 2 gaariyan aik sath aayen to pehle kon jaye:", options: ["The vehicle on the right", "The bigger vehicle", "Whoever is faster", "The vehicle turning left"], correctIndex: 0, explanation: "When arriving simultaneously, the vehicle to the right typically has the right of way." },
  { id: "row_04", category: "Right of Way", question_en: "A vehicle turning left must yield to:", question_ur: "Left turn lene wali gaari ko kis ko yield karna chahiye:", options: ["Oncoming straight-moving traffic", "Parked vehicles", "Traffic behind it", "Pedestrians on the sidewalk only"], correctIndex: 0, explanation: "Vehicles making a turn must give way to oncoming traffic that is moving straight through the intersection." },
  { id: "row_05", category: "Right of Way", question_en: "On a narrow mountain road, which vehicle typically has the right of way?", question_ur: "Tang pahari road par kis gaari ko right of way milta hai:", options: ["The vehicle going downhill", "The vehicle going uphill", "The faster vehicle", "The smaller vehicle"], correctIndex: 1, explanation: "The vehicle climbing uphill usually has the right of way since it's harder to restart on an incline; the downhill vehicle should reverse or yield to a passing point." },
  { id: "row_06", category: "Right of Way", question_en: "Emergency vehicles (ambulance, fire brigade) with sirens on:", question_ur: "Ambulance ya fire brigade jab siren ke sath ho to:", options: ["Have priority over all other traffic", "Must wait like everyone else", "Only have priority at night", "Have priority only on motorways"], correctIndex: 0, explanation: "Emergency vehicles with active sirens always have priority, and all other traffic must yield and clear the path." },
  { id: "row_07", category: "Right of Way", question_en: "When merging onto a motorway from a slip road, you should:", question_ur: "Slip road se motorway par merge karte waqt kya karna chahiye:", options: ["Force your way in", "Match speed and merge safely when there's a gap", "Stop and wait on the slip road", "Merge immediately regardless of traffic"], correctIndex: 1, explanation: "Merging traffic should match the motorway's speed and merge into a safe gap; motorway traffic generally has priority." },
  { id: "row_08", category: "Right of Way", question_en: "At a T-junction, traffic on the through road (the top of the T) has right of way over:", question_ur: "T-junction par through road (top of T) ko kis par right of way hota hai:", options: ["Traffic joining from the side road", "Pedestrians", "No one", "Cyclists only"], correctIndex: 0, explanation: "Vehicles on the main through road have priority over vehicles joining from the side road at a T-junction." },

  // SAFE DRIVING PRACTICES
  // Replaces the old "Penalties" category, which had no basis in the NH&MP theoretical
  // test syllabus (that document has no fines/penalties section — it's a Sign Test +
  // Rules Test only). These are drawn directly from the official question bank instead.
  { id: "safe_01", category: "Safe Driving Practices", question_en: "Use of a helmet is _____ for motorcyclists.", question_ur: "Motorcyclists ke liye helmet use karna:", options: ["Mandatory", "Unnecessary", "Not safe", "Optional"], correctIndex: 0, explanation: "Per the NH&MP syllabus, helmet use is mandatory for motorcyclists." },
  { id: "safe_02", category: "Safe Driving Practices", question_en: "Reading or sending an SMS while driving is allowed?", question_ur: "Gaari chalatay waqt SMS parhna ya bhejna allowed hai?", options: ["No", "Do not know", "Yes", "Below 80 km/h it's fine"], correctIndex: 0, explanation: "Reading or sending SMS while driving is not allowed under any circumstance." },
  { id: "safe_03", category: "Safe Driving Practices", question_en: "You are following a vehicle on a wet road. You should leave a time gap of at least:", question_ur: "Gaili road par aagay wali gaari se kam az kam kitna time gap rakhna chahiye:", options: ["One second", "Two seconds", "Three seconds", "Four seconds"], correctIndex: 3, explanation: "On a wet road, leave at least a four-second gap since stopping distances increase significantly." },
  { id: "safe_04", category: "Safe Driving Practices", question_en: "If your vehicle's tyre bursts at the rear while driving, you should:", question_ur: "Chalte huay agar peechay ka tyre burst ho jaye to kya karna chahiye:", options: ["Swiftly turn the wheel to adjust", "Firmly hold the steering wheel with both hands", "Swiftly turn toward the opposite direction", "Immediately slam the brakes"], correctIndex: 1, explanation: "On a tyre burst, firmly hold the steering wheel with both hands to keep the vehicle stable — do not brake suddenly." },
  { id: "safe_05", category: "Safe Driving Practices", question_en: "What should you do first after being involved in a road accident?", question_ur: "Accident hone ke baad sab se pehle kya karna chahiye:", options: ["Stop", "Run", "Panic", "All of the above"], correctIndex: 0, explanation: "Your first responsibility after an accident is to stop, not to flee the scene." },
  { id: "safe_06", category: "Safe Driving Practices", question_en: "It is illegal for a driver to use a cell phone while driving.", question_ur: "Driving ke doran mobile phone use karna illegal hai.", options: ["Right", "Wrong", "I don't know", "None of them"], correctIndex: 0, explanation: "Using a cell phone while driving is illegal, per the NH&MP theoretical test syllabus." },
  { id: "safe_07", category: "Safe Driving Practices", question_en: "Continuously using the foot brake on a long downhill road:", question_ur: "Lambay downhill road par mustaqil foot brake use karna:", options: ["Can shorten the engine's life", "Increases driver fatigue", "Can drastically reduce braking efficiency due to rising brake temperature", "Can easily cause the vehicle to overturn"], correctIndex: 2, explanation: "Riding the brakes continuously on a long descent overheats them and drastically reduces braking efficiency — use a lower gear instead." },
];
